### ISSUE TITLE
Highlight the object selected in Object Tree

### ISSUE THREAD

**Issue by pklimai** [mipt-npm/dataforge-vis#10]
Also, show object name in the Properties editor.
Maybe also allow to select an object by double-clicking on it in the visualization screen, if possible.

**Comment by altavir** [comment]
Implemented both. There is still a problem with highlighting by mouse in MM demo since the tree represents groups, but actual blocks are anonimous blocks. We will need to address it for actual display by providing custom redirects for raytracing targets (the simplest way is to redirect to nearest named parent) as well as by providing custom configuration capabilities for editors. 

Also it is not currently possible to jump to object in a tree since tree widget is rather primitive.
